---
- hosts: localhost
  tasks:
  - name: "Copy config files"
    copy:
      src: "{{ item }}"
      dest: "~/{{ item }}"
    loop:
    - ".bash_aliases"
    - ".bashrc"
    - ".dir_colors"
    - ".gitconfig"
    - ".gvimrc"
    - ".kubectl_aliases"
    - ".rpmmacros"
    - ".vimrc"
    - ".Xdefaults"

  - name: "Copy config dirs"
    copy:
      src: "{{ item }}"
      dest: "~"
    loop:
    - ".config"
    - ".byobu"

  - name: "Unpack .vim dir"
    unarchive:
      src: .vim.tar.gz
      dest: "~"
      creates: "~/.vim/bundle/nerdtree"
