---
- hosts: localhost
  tasks:
  - name: "Copy files"
    copy:
      src: "{{ item }}"
      dest: "~/{{ item }}"
    loop:
    - ".bash_aliases"
    - ".bashrc"
    - ".dir_colors"
    - ".gitconfig"
    - ".gvimrc"
    - ".kubectl_aliases"
    - ".rpmmacros"
    - ".vimrc"
    - ".Xdefaults"

  - name: "Copy dirs"
    copy:
      src: "{{ item }}"
      dest: "~"
    loop:
    - ".config"
    - ".byobu"
    - ".ssh"
    - ".local"

  - name: "Unpack .vim dir"
    unarchive:
      src: .vim.tar.gz
      dest: "~"
      creates: "~/.vim/bundle/nerdtree"
